### ISSUE TITLE
32-bit integer limit

### ISSUE THREAD

**Issue by elliotwutingfeng** [tjblackheart/andcli#6]
json.Unmarshal fails on 32-bit systems like Windows 10 32-bit edition because the **LastUsed  int `json:"last_used"** field in **andotp.go** is larger than the 32-bit integer limit. This could be remedied with explicit **int64** typing.

**Comment by tjblackheart** [comment]
Thank you. Now, I really wonder who would use a 32bit Windows 10 ...
